[package]
name = "art_portfolio_yew"
version = "0.0.1"
authors = ["Aaron Cook <aarongregorycook@gmail.com>"]
repository = "https://github.com/cookthebook/ArtPortfolioYew"

[dependencies]
yew = "0.4.0"
cargo-web = "0.6.19"
